config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:sessions]
    as :user do
      get '/users/sign_in' => 'sessions#new', as: 'new_user_session'
      post '/users/sign_in' => 'sessions#create', as: 'user_session'
      delete '/users/sign_out' => 'sessions#destroy', as: 'destroy_user_session'
    end

  resources :users

  root 'questions#index'

  concern :votable do
    get :vote, on: :member
  end

  resources :answers, concerns: :votable

  resources :questions, concerns: :votable do
    get :tagged, on: :collection, to: :index
  end

  scope :api, constraints: { format: :json } do
    resources :questions, :answers, only: [:index, :show]
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  include IdFriendable
  include PostAccessable

  belongs_to :user
  has_many :answers
  has_one :post, as: :postable, required: true

  acts_as_taggable_on :tags

  accepts_nested_attributes_for :post

  validates :header, presence: :true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include SharedBeforeFilters
  include CalculateVotes

  before_action :set_tag_cloud, only: [:index, :show, :tagged]
  before_action :update_number_of_views, if: :loggedin_and_not_author?, only: [:show]
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.preload(:user, :post).order('created_at DESC').page(params[:page]).per(10)

    @questions = @questions.tagged_with(params[:tag]) if params[:tag]
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
    @question.build_post
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new question_params.merge user_id: current_user.id
    @question.build_post embedded_post_params

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def vote
    @cid = @question.cid
    @total_votes = calculate_votes()

    if @question.post.update(votes: @total_votes)
      respond_to do |format|
        format.js { render 'shared/update_votes.js.erb' }
      end
    end
  end

  private
  def set_entity
    @question = Question.find(params[:id])
  end

  def set_tag_cloud
    @tags = Question.tag_counts_on(:tags)
  end

  def set_vote
    @vote = VotesCloud.find_or_create_by(user_id: current_user.id, "#{@question.namespace}_id": @question.id)
  end

  def set_current_votes_number
    @entity_current_votes = @question.votes
  end

  def loggedin_and_not_author?
    user_signed_in? && @question.user_id != current_user.id
  end

  def update_number_of_views
    views = ViewsCloud.where(user_id: current_user.id, question_id: @question.id)

    unless views.exists?
      @question.update(views: @question.views + 1)
      views.create!
    end
  end

  def question_params
    params.require(:question).permit(:header, :tag_list)
  end

  def embedded_post_params
    params.require(:question).permit(post_attributes: :body)[:post_attributes]
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/questions/_form.html.slim
= form_for(@question) do |f|
  - if @question.errors.any?
    #error_explanation
      h2
        = pluralize(@question.errors.count, "error")
        | prohibited this question from being saved:
      ul
        - @question.errors.full_messages.each do |message|
          li= message
  .field
    = f.label :header
    br/
    = f.text_field :header
    br/
    = f.fields_for :post do |post_form|
      = post_form.text_area :body, placeholder: 'Describe your issue here...'
  .field
    = f.label :tags
    = f.text_field :tag_list
  .actions
    = f.submit

app/views/questions/_tag_cloud.html.slim
div
  - tag_cloud(tags, %w(css1 css2 css3 css4)) do |tag, css_class|
    = link_to "#{tag.name} #{tag.taggings_count}", tagged_questions_path(tag: tag.name), class: css_class

app/views/questions/edit.html.slim
h1 Editing Question
= render 'form'
= link_to 'Show', @question

app/views/questions/index.html.slim
div style='float:left;width:60%'
  h1 Questions
  table
    tbody
      - @questions.each do |question|
        tr
          td rowspan='2'
            = "#{question.votes} Votes"
          td rowspan='2'
            = "#{question.answers.count} Answers"
          td rowspan='2'
            = "#{question.views} Views"
          td colspan='2'
            h4 = link_to question.header, question
        tr
          td colspan='2'
            = render partial: 'tag_cloud', locals: { tags: @tags }
          td = "#{question.user.avatar} #{question.user.email}"
          / td= link_to 'Show', question
          / td= link_to 'Edit', edit_question_path(question)
          / td= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' }
  br/
  = paginate @questions

app/views/questions/new.html.slim
h1 New Question
= render 'form'

app/views/questions/show.html.slim
div
  table
    tbody
      tr
        td colspan='2'
          strong= @question.header
      tr
        td id=@question.cid data-user= current_user.try(:id)
          = render partial: 'shared/votes', locals: { entity: @question }
        td= @question.post.body
      tr
        td= "#{@question.views} Views"
        td
          / p= @question.user.avatar
          / p= @question.user.emai
      tr
        td colspan='2'
          = render partial: 'tag_cloud', locals: { tags: @tags }

  = link_to 'Edit', edit_question_path(@question)
  | \
  = link_to 'Back', questions_path
hr
div
  = render partial: 'answers/index', locals: { answers: @question.answers, question_id: @question.id }