config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:sessions]
    as :user do
      get '/users/sign_in' => 'sessions#new', as: 'new_user_session'
      post '/users/sign_in' => 'sessions#create', as: 'user_session'
      delete '/users/sign_out' => 'sessions#destroy', as: 'destroy_user_session'
    end

  resources :users

  root 'questions#index'

  concern :votable do
    get :vote, on: :member
  end

  resources :answers, concerns: :votable

  resources :questions, concerns: :votable do
    get :tagged, on: :collection, to: :index
  end

  scope :api, constraints: { format: :json } do
    resources :questions, :answers, only: [:index, :show]
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include IdFriendable
  include PostAccessable

  belongs_to :user
  belongs_to :question, required: true
  has_one :post, as: :postable, required: true

  accepts_nested_attributes_for :post
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include SharedBeforeFilters
  include CalculateVotes

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.joins(:post).order('votes DESC')
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new answer_params.merge user_id: current_user.id
    @answer.build_post embedded_post_params
      respond_to do |format|
        if @answer.save
          format.js { render 'load_answer' }
        else
          format.js { render 'empty_form_alert' }
        end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.post.update(embedded_post_params)
        format.js { head :no_content }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def vote
    @cid = @answer.cid
    @total_votes = calculate_votes()

    if @answer.post.update votes: @total_votes
      respond_to do |format|
        format.js { render 'shared/update_votes.js.erb' }
      end
    end
  end

  private
  def set_entity
    @answer = Answer.find(params[:id])
  end

  def set_vote
    @vote = VotesCloud.find_or_create_by(user_id: current_user.id, "#{@answer.namespace}_id": @answer.id)
  end

  def set_current_votes_number
    @entity_current_votes = @answer.votes
  end

  def answer_params
    params.require(:answer).permit(:question_id)
  end

  def embedded_post_params
    params.require(:answer).permit(post: :body)[:post]
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer_item.html.slim
tr.answer data-id= answer.id
  td id=answer.cid class='votes-container' data-user= current_user.try(:id)
    = render partial: 'shared/votes', locals: { entity: answer }
  td.description
    div = answer.post.body
  / td= link_to 'Show', answer
  td
    div.edit.green-button style='display:none;'
      = 'Edit'
  / td= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' }
tr
  td colspan='2'
    p= answer.user.avatar
    p= answer.user.email

app/views/answers/_form.html.slim
= form_for :answer, url: answers_path, method: :post, remote: true do |f|
  .field
    = f.fields_for :post do |post_form|
      = post_form.text_area :body, placeholder: 'Answer me here..'
  .field
    = f.hidden_field :question_id, { value: question_id }
  .actions
    = f.submit 'Create'

app/views/answers/_index.html.slim
h1= "#{answers.count} Answers"
table
  tbody#answers_stack
    - answers.each do |answer|
      = render partial: 'answers/answer_item', locals: { answer: answer }
br/
= render partial: 'answers/form', locals: { question_id: question_id }

app/views/answers/empty_form_alert.js.erb
$('p.alert').text('Answer Body Cannot Be Empty!');

app/views/answers/load_answer.js.erb
$('#answers_stack').append('<%= j(render partial: "answer_item", locals: { answer: @answer }) %>');