config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:sessions]
    as :user do
      get '/users/sign_in' => 'sessions#new', as: 'new_user_session'
      post '/users/sign_in' => 'sessions#create', as: 'user_session'
      delete '/users/sign_out' => 'sessions#destroy', as: 'destroy_user_session'
    end

  resources :users

  root 'questions#index'

  concern :votable do
    get :vote, on: :member
  end

  resources :answers, concerns: :votable

  resources :questions, concerns: :votable do
    get :tagged, on: :collection, to: :index
  end

  scope :api, constraints: { format: :json } do
    resources :questions, :answers, only: [:index, :show]
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title KnowledgeOverflow
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    p.notice style='position:fixed;color:MediumSeaGreen;font: bold 12px Tahoma;' = notice
    p.alert style='position:fixed;color:Tomato;font: bold 12px Tahoma;' = alert
    div#topbar.navigation-bar
      div.section.profile-button
        = link_to 'Sign up', new_user_registration_path
      div.section.profile-button
        = link_to 'Sign in', new_user_session_path
    div.navigation-bar
      div.section.navigation-button
        = link_to 'Ask Question', new_question_path
      div.section.navigation-button
        = link_to 'Users', users_path
      div.section.navigation-button
        = link_to 'Questions', questions_path
    = yield